# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'CropViewController'
pod 'ObjectMapper'

pod 'NVActivityIndicatorView'
pod 'SDWebImage'
pod 'Alamofire', '~> 4.0'
pod 'SOTabBar'
pod 'LGSideMenuController'

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Firebase/Database'

  # Pods for MoviesDemo

end
